# I'm thinking I'll just keep it as a binary name, nothing fancy
# So what do we keep here? Key: app_id, Value: (path, hash)
[apps."brave"]
path = "/opt/brave-bin/brave"
hash = "sha256:fedcba654321..." 

[apps."systemd-resolved"]
path = "/usr/lib/systemd/systemd-resolved"
hash = "sha256:fedcba654321..."

[apps."ssh"]
path = "ssh"
hash = "sha256:fedcba654321..."

[apps."ping"]
path = "/usr/bin/ping"
hash = "sha256:fedcba654321..."

[apps."curl"]
path = "/usr/bin/curl"
hash = "sha256:fedcba654321..."

[apps."vscodium"]
path = "/opt/vscodium-bin/codium"
hash = "sha256:fedcba654321..."

[apps."discord"]
path = "/opt/discord/Discord"
hash = "sha256:fedcba654321..."

[apps."firewhal-discord-bot"]
path = "/opt/firewhal/bin/firewhal-discord-bot"
hash = "sha256:fedcba654321..."

[apps."zoom-frontend"]
path = "/opt/zoom/ZoomWebviewHost"
hash = "sha256:fedcba654321..."

[apps."zoom"]
path = "/opt/zoom/zoom"
hash = "sha256:fedcba654321..."