# apps = {}


[apps.sshd]
path = "/usr/bin/sshd"
hash = "8d127c26993ea530f01110387aaf0c6bb445d3dbd540c461875952d7fd5ec333"


[apps.NetworkManager]
path = "/usr/bin/NetworkManager"
hash = "31233da1c91bb113f77c71b7a84f855d4d4e0385ff8c062521b249bed3259356"

[apps.systemd-resolved]
path = "/usr/lib/systemd/systemd-resolved"
hash = "b7f853744bc0b5fa84f764dc61a6d0f214efdcfff08b4fc31a8138e81f5435b6"


[apps.firewhal-daemon]
path = "/usr/local/sbin/firewhal-daemon"
hash = "3e3d14e8aea2fa9accfaf7bda9e2601ae1e3617c889c29a6c395e974437a540b"

[apps.brave]
path = "/opt/brave-bin/brave"
hash = "fd9a267f3514f738c2d33a9749c15f5a2d9ebad1a3aedac420de3deab7b6fb05"