[apps.Discord]
path = "/opt/discord/Discord"
hash = "12d6707e5d14aecfb35d3c43a1395318134af0b52d5b566c4820bf8efe6d893c"

[apps.NetworkManager]
path = "/usr/bin/NetworkManager"
hash = "617599123153495d709e9639d67e9c8495e5d0d6add0b32be4594e76dd89ca42"

[apps.ping]
path = "/usr/bin/ping"
hash = "d99fc96281f3ea11913f9ff3b750ce6fbd5d0c84035c2f93dc52c0bb9fa3144b"

[apps.systemd-resolved]
path = "/usr/lib/systemd/systemd-resolved"
hash = "40d031e9d88fb23b715fccce3da1adc74017d5c6e553969e561be0943e6e9b4a"

[apps.brave]
path = "/opt/brave-bin/brave"
hash = "96e979373ba7635248086fe5e87ecc9f33421460bf593a19ca35cdcc89db34d8"

[apps.firewhal-daemon]
path = "/usr/local/sbin/firewhal-daemon"
hash = "debb04a345a1cfcba2992cbcef39f7c3529f54e4669bd34edf9b2dbd951838c6"

[apps.codium]
path = "/opt/vscodium-bin/codium"
hash = "de3df78022e8e63941de42da1acca55268eef022540eabfb8a3071760d1c0409"

[apps.curl]
path = "/usr/bin/curl"
hash = "00c5d31285b525975f526a2c2ce8365a1b545f6fe003a9ded69f7198f67b8f9c"

[apps.ssh]
path = "/usr/bin/ssh"
hash = "e21c8774a91322e81eb84922ae6719b30ede7efc194346991922f8c6cbb2940a"
