[package]
name = "firewhal-ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
bytes = "1.11.0"
firewhal-core = { path = "../firewhal-core" } # Depends on the shared library
nix = { version = "0.30.1", features = ["fs", "user"] }
tokio = "1.48.0"
zeromq = "0.4.1"

