[package]
name = "firewhal-ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
firewhal-core = { path = "../firewhal-core" } # Depends on the shared library
nix = { version = "0.30.1", features = ["fs", "user"] }
zmq = "0.10.0"
