[package]
name = "firewhal-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
zmq = { workspace = true }
