[package]
name = "firewhal-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2.0.1"
serde = "1.0.226"
tokio = { version = "1.45.1", features = ["signal", "sync", "rt", "rt-multi-thread", "macros", "time"] }
zmq = "0.10.0"
